/** Run status of a node */
export type RunStatus =
  | 'idle'
  | 'queued'
  | 'running'
  | 'success'
  | 'error'
  | 'skipped'
  | 'cancelled';

/** A node on the canvas — a computational unit with prompt and generated output */
export interface BreakdownNode {
  id: string;
  graph_id: string;
  node_type: string;
  name: string;
  position_x: number;
  position_y: number;

  /** User-written task/instruction */
  prompt: string;
  /** Generated by Claude on run — null until first run */
  output: string | null;
  /** Current execution state */
  run_status: RunStatus;
  /** Error message if run_status is error, skipped, or cancelled */
  run_error: string | null;
  /** ISO timestamp of last successful run */
  last_run_at: string | null;

  /** Flexible metadata for future use */
  metadata: Record<string, unknown>;

  created_at: string;
  updated_at: string;
}

export type ThesisNode = BreakdownNode;
